# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "caio2k/ubuntu-devel"

  config.vm.provider :libvirt do |libvirt, override|
    libvirt.memory     = '2048'
    libvirt.channel :type => 'spicevmc', :target_name => 'com.redhat.spice.0', :target_type => 'virtio'
    libvirt.graphics_type = 'spice'
    libvirt.video_type = 'qxl'
    libvirt.sound_type = 'ac97'
    libvirt.storage :file, :size => '40G', :type => 'raw', :allow_existing => true
    libvirt.random :model => 'random'
  end

end
